version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: 
      - ./DeNovoCNN.wdl
    testParameterFiles:
      - ./DeNovoCNN.json
    readMePath: https://github.com/lizhebio/DeNovoCNN/blob/master/README.md
    authors:
      - orcid: 0000-0002-5151-6109
