version: 1.2
workflows:
  - name: DeNovoCNN
    subclass: WDL
    primaryDescriptorPath: /DeNovoCNN.wdl
    testParameterFiles:
      - /DeNovoCNN.json
    readMePath: /README.md
    authors:
      - orcid: https://orcid.org/0000-0002-5151-6109

